name: Release Build

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: mhws-tex-decompressor

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Build
        run: cargo build --verbose --release

      - name: Prepare release package
        run: |
          New-Item -ItemType Directory -Force -Path release | Out-Null
          $destination = "release/${{ env.BINARY_NAME }}-x86_64-pc-windows-msvc.zip"
          Compress-Archive -Path "target/release/${{ env.BINARY_NAME }}.exe" -DestinationPath $destination -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-x86_64-pc-windows-msvc
          path: release/${{ env.BINARY_NAME }}-x86_64-pc-windows-msvc.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          generate_release_notes: true
          files: release/${{ env.BINARY_NAME }}-x86_64-pc-windows-msvc.zip
          name: Release ${{ github.ref_name }}
          body: |
            ## ${{ github.ref_name }}

            ### Changes
            - Please fill in the changes
